[package]
name = "harbory-agent"
edition.workspace = true
version.workspace = true

[dependencies]
harbory-protocol = { path = "../protocol" }
harbory-common = { path = "../common" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
