root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  exclude_dir = ["tmp", "vendor"]
  args_bin = ["--config", "./config/local.yaml"]

[log]
  time = true